

WINDOW_TITLE = 'NvTuner'
WINDOW_SIZE = '300x350'
MAIN_FONT = ('Open Sans', 9)
MAIN_FONT_BOLD = ('Open Sans', 10, 'bold')
COLOR_BG0 = '#222'
COLOR_BG1 = '#333'
COLOR_TEXT = '#DDD'
COLOR_TEXT_TITLE = '#FFF'