
# Defines from https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__nvapitypes.html
NVAPI_SHORT_STRING_MAX = 64
NVAPI_LONG_STRING_MAX = 256
NVAPI_GENERIC_STRING_MAX = 4096
NVAPI_MAX_PHYSICAL_GPUS = 64
NVAPI_PHYSICAL_GPUS = 32
NVAPI_MAX_THERMAL_SENSORS_PER_GPU = 3
NVAPI_MAX_COOLERS_PER_GPU = 3
NVAPI_MAX_GPU_PSTATE20_PSTATES = 16
NVAPI_MAX_GPU_PSTATE20_CLOCKS = 8
NVAPI_MAX_GPU_PSTATE20_BASE_VOLTAGES = 4
NVAPI_MAX_GPU_PUBLIC_CLOCKS = 32